import type { Task, Suggestion } from "./types"

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Tighten hinge screws downstairs cabinet",
    originalText: "Fix that damn cabinet downstairs",
    context: "Home repair",
    eta: "3 minutes",
    friction: "low",
    bestTime: "anytime",
    patternMatch: "You tend to delay this category for 30 days",
    status: "pending",
    microMoves: ["Buy missing screws", "Tighten hinge"],
    isHireOutCandidate: true,
    aiTags: ["Home repair", "Low friction", "Self or hire"],
    aiRecommendation: "Best time: morning meeting window",
    energyLevel: "medium",
    priority: "low",
    estimatedMinutes: 3,
    surveillance: false,
  },
  {
    id: "2",
    title: "Send KDMC invoice",
    context: "Business",
    eta: "2 min",
    status: "pending",
    friction: "low",
    aiTags: ["Work", "Money", "Quick win"],
    aiRecommendation: "Best time: now",
    energyLevel: "medium",
    priority: "high",
    estimatedMinutes: 2,
    surveillance: false,
    bestTime: "now",
  },
  {
    id: "3",
    title: "Order blackout curtains",
    context: "Home",
    eta: "5 min",
    status: "pending",
    friction: "low",
    aiTags: ["Home", "Online task"],
    aiRecommendation: "Best time: evening wind-down",
    energyLevel: "low",
    priority: "medium",
    estimatedMinutes: 5,
    surveillance: false,
    bestTime: "evening_wind_down",
  },
  {
    id: "4",
    title: "Hire handyman for cabinet",
    context: "Home repair",
    eta: "10 min",
    status: "pending",
    expiresAt: new Date(),
    friction: "medium",
    aiTags: ["Vendor", "Home repair"],
    aiRecommendation: "Recommended: morning",
    energyLevel: "medium",
    priority: "medium",
    estimatedMinutes: 10,
    surveillance: false,
    bestTime: "morning_meeting_window",
  },
  {
    id: "5",
    title: "Prep Thursday financial docs",
    context: "Business",
    eta: "25 min",
    status: "pending",
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    friction: "medium",
    aiTags: ["Money", "Deep work"],
    aiRecommendation: "Best time: focus block",
    energyLevel: "peak",
    priority: "high",
    estimatedMinutes: 25,
    surveillance: false,
    bestTime: "focus_block",
  },
  {
    id: "6",
    title: "Order Sully's medicine",
    context: "Family",
    eta: "5 min",
    status: "pending",
    expiresAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    friction: "low",
    aiTags: ["Family", "Urgent", "Quick win"],
    aiRecommendation: "Do immediately",
    energyLevel: "medium",
    priority: "high",
    estimatedMinutes: 5,
    surveillance: true,
    bestTime: "now",
  },
]

export const mockSuggestions: Suggestion[] = [
  {
    id: "1",
    text: "Break KDMC flowsheet issue into 3 micro moves",
    actionLabel: "Break down",
  },
  {
    id: "2",
    text: "You tend to delay home repairs. Want to auto route these to Hire Out?",
    actionLabel: "Yes",
  },
]
